name: "Olga Bonitas"
picture: "picture.jpg" # paste an img at root of project or an image source url
#bio: ""
meta:
  lang: "en"
  description: "Watercolour artist and sketchbook lover based in London"
  title: "Olga Bonitas"
  author: "Olga Bonitas"
  siteUrl: "https://olgabonitas.com"
links:
  - name: "My Approach to Sketchbooks & Art Journaling. Skillshare Series"
    url: "https://olga-bonitas.com/blog/my-approach-to-sketchbooks-art-journaling"
  - name: "FREE Guide to Art Journaling ðŸ’«"
    url: "https://olgabonitas.myflodesk.com/artjournalguide"
  - name: "All classes"
    url: "https://olga-bonitas.com/classes"
  - name: "Warm letter from me every month"
    url: "https://olgabonitas.myflodesk.com/warmletter"
  - name: "My Illustrations"
    url: "https://olga-bonitas.com/illustrations"
  - name: "YouTube"
    url: "https://www.youtube.com/@olgabonitas/videos"
theme: "custom"